---
all:
  vars:
    ansible_port: 1377
    ansible_user: ubuntu
  children:
    home:
      hosts:
        home:
      children:
        my:
          hosts:
            my.home:  # my.home host
          children:
            system-00:
              hosts:
                system-00.my.home:  # system-00.my.home host
              children:
                dns:
                  hosts:
                    dns-00.system-00.my.home:  # DNS hosts
                component:
                  hosts:
                    component-03.system-00.my.home:  # Component hosts
                vpn:
                  hosts:
                    vpn-00.system-00.my.home:  # VPN hosts
                    vpn-01.system-00.my.home: 
                      ansible_port: 22
                database:
                  hosts:
                    database-01.system-00.my.home:  # Database hosts
                    database-02.system-00.my.home:
                    database-03.system-00.my.home:
                balancer:
                  hosts:
                    balancer-00.system-00.my.home:  # Balancer hosts
                    balancer-01.system-00.my.home:
                utility:
                  hosts:
                    utility-00.system-00.my.home:  # Utility hosts
                share:
                  hosts:
                    share-00.system-00.my.home:  # Share hosts
                    # Add other share hosts here
                legacy:
                  hosts:
                    legacy-00.system-00.my.home:  # Legacy hosts
                suiteux-data:
                  hosts:
                    suiteux-data.system-00.my.home:  # SuiteUX-Data hosts
            staging-00:
              hosts:
                staging-00.system-00.my.home:  # Staging hosts
              children:
                edge:
                  hosts:
                    edge-0000.staging-00.my.home:  # Edge hosts for staging
                    edge-0001.staging-00.my.home:
                database:
                  hosts:
                    database-01.staging-00.my.home:  # Database hosts for staging
                spool:
                  hosts:
                    spool-00.staging-00.my.home:  # Spool hosts for staging
            garet:
              hosts:
                garet.my.home:  # Garet hosts
            myproject:
              hosts:
                enhancemancer.my.home:  # Enhancemancer hosts
            michelle:
              hosts:
                michelle.my.home:  # Michelle hosts
            tom:
              hosts:
                tom.my.home:  # Tom hosts
            git:
              hosts:
                git.my.home:  # Git hosts
        mypublication:
          hosts:
            mypublication.home:  # Custom publishing project hosts (internet facing)
            # Add other avenuepad hosts here
    orchestra:
      hosts:
        orchestra.private:  # Orchestra hosts
      children:
        signin:
          hosts:
            signin.orchestra.private:  # Signin hosts
        conductor:
          hosts:
            conductor.orchestra.private:  # Conductor hosts
    secure:
      hosts:
        secure.private:  # Secure hosts
