---
- hosts: balancer
  name: Add users & groups
  become: true
  tasks:
    - name: Add group "superuser" to remote server
      ansible.builtin.group:
        name: superuser
        state: present
        gid: 81919

    - name: Add group "fullstack" to remote server
      ansible.builtin.group:
        name: fullstack
        state: present
        gid: 81917

    - name: Add group "work" to remote server
      ansible.builtin.group:
        name: work
        state: present
        gid: 81916

    - name: Add group "render" to remote server
      ansible.builtin.group:
        name: render
        state: present
        gid: 81916

    - name: Add group "resource" to remote server
      ansible.builtin.group:
        name: resource
        state: present
        gid: 81915

    - name: Add group "component" to remote server
      ansible.builtin.group:
        name: component
        state: present
        gid: 81915

    - name: Add group "composition" to remote server
      ansible.builtin.group:
        name: composition
        state: present
        gid: 81913

    - name: Add group "service" to remote server
      ansible.builtin.group:
        name: service
        state: present
        gid: 81912

    - name: Add group "instrument" to remote server
      ansible.builtin.group:
        name: instrument
        state: present
        gid: 81911

    - name: Add group "ensemble" to remote server
      ansible.builtin.group:
        name: ensemble
        state: present
        gid: 81914

    - name: Add group "orchestra" to remote server
      ansible.builtin.group:
        name: orchestra
        state: present
        gid: 81918

    - name: Create user Garet
      ansible.builtin.user:
        name: garet
        state: present
        comment: "Garet Claborn"
        createhome: false
        group: sudo
        groups:
          - superuser
          - fullstack
          - security
          - ensemble
          - orchestra
          - render
          - resource
          - component
          - composition
          - service
          - work
        uid: 73824

    - name: Create user Tom
      ansible.builtin.user:
        name: tom
        state: present
        comment: "Tom Samwel"
        createhome: false
        group: sudo
        groups:
          - superuser
          - fullstack
          - security
        uid: 73825

    - name: Create user me
      ansible.builtin.user:
        name: me
        state: present
        comment: "myhome"
        createhome: true
        group: orchestra
        groups:
          - orchestra
          - ensemble
          - instrument
        uid: 81920

